apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-backend-deployment
  labels:
    app: quiz-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-backend
  template:
    metadata:
      labels:
        app: quiz-backend
    spec:
      containers:
        - name: quiz-backend
          image: quiz-backend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: quiz-config
            - secretRef:
                name: quiz-secrets
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-mongodb-deployment
  labels:
    app: quiz-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-mongodb
  template:
    metadata:
      labels:
        app: quiz-mongodb
    spec:
      containers:
        - name: quiz-mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-redis-deployment
  labels:
    app: quiz-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-redis
  template:
    metadata:
      labels:
        app: quiz-redis
    spec:
      containers:
        - name: quiz-redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-backend-service
  labels:
    app: quiz-backend
spec:
  type: NodePort
  selector:
    app: quiz-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-mongodb-service
  labels:
    app: quiz-mongodb
spec:
  type: ClusterIP
  selector:
    app: quiz-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-redis-service
  labels:
    app: quiz-redis
spec:
  type: ClusterIP
  selector:
    app: quiz-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quiz-config
data:
  MONGO_URI: mongodb://quiz-mongodb-service:27017/quiz-app
  REDIS_URL: redis://quiz-redis-service:6379
---
apiVersion: v1
kind: Secret
metadata:
  name: quiz-secrets
type: Opaque
data:
  JWT_SECRET: c2VjdXJlc2VjcmV0ZXhhbXBsZQ== # "securesecretexample" encoded in base64
